from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, Tuple

import numpy as np
from scipy.interpolate import PchipInterpolator
from scipy.linalg import eig
from scipy.optimize import lsq_linear

from ..base import MeasureTransform
from ..config import BootstrapSpec, CacheSpec, KeySpec
from ..moments import physical_moments_table
from ..output import (
    build_axis_grids,
    build_transform_output,
    lr_surface_to_k_surface,
    lr_surface_to_r_surface,
)
from ..registry import register_transform
from ..utils import (
    _as_1d,
    _cdf_from_density,
    _find_spot,
    _trapz_normalize_density,
)


@dataclass
class RossRecoveryOutput:
    state_price_matrix: np.ndarray
    state_price_transition: np.ndarray
    physical_transition: np.ndarray
    eigenvalue: float
    eigenfunction: np.ndarray
    pricing_kernel_recovery_grid: np.ndarray
    ridge_zeta: float
    kl_loss: float
    current_state_index: int
    transition_step_days: int
    transition_step_years: float
    transition_pair_count: int
    transition_source_indices: np.ndarray
    transition_target_indices: np.ndarray
    kl_maturity_indices: np.ndarray
    dominant_eigenvalue: float
    subdominant_eigenvalue_abs: float
    subdominant_to_dominant_ratio: float
    eigenpair_residual: float
    recovered_transition_row_sum_error: float
    transition_system_rows: int
    transition_system_columns: int
    transition_system_rank: int
    transition_system_condition_number: float
    transition_fit_rmse: float
    transition_fit_relative_rmse: float
    transition_matrix_zero_fraction: float
    transition_matrix_min_row_sum: float
    transition_matrix_max_row_sum: float
    selected_kl_reconstruction_rmse: float
    selected_kl_reconstruction_relative_rmse: float
    zeta_values_tested: np.ndarray
    zeta_kl_values: np.ndarray
    diagnostic_warnings: Tuple[str, ...]
    recovery_grid: np.ndarray
    recovery_grid_size: int
    original_grid_size: int
    recovery_grid_bounds: Tuple[float, float]


@register_transform("ross_recovery")
@register_transform("ross")
class RossRecoveryKernel(MeasureTransform):
    """
    Audrino-Huitema-Ludwig style regularized Ross recovery.

    Main implementation choices
    ---------------------------
    1. The transition state-price matrix is estimated from maturity pairs
       separated by ``transition_step_days`` rather than from adjacent tenors.

    2. For each ridge penalty, the transition matrix is estimated by
       nonnegative Tikhonov-regularized least squares:

           min_{p_j >= 0} ||A p_j - b_j||_2^2 + zeta ||p_j||_2^2.

    3. The ridge penalty is selected by generalized KL discrepancy between
       observed state prices and the state prices generated by unrolling the
       estimated transition matrix.

    4. The right Perron eigenvector z is recovered on the coarse state grid.
       The pricing kernel is proportional to 1/z.

    5. The recovered Perron vector z is interpolated back to the original
       fine state grid using PCHIP. This shape-preserving interpolator avoids
       the negative overshoot that can occur with ordinary cubic splines.
       Physical probability masses at
       each observed maturity are then obtained directly as

           recovered_mass_j(x) proportional to z(x) * state_price_mass_j(x).

       The same state-dependent pricing kernel is therefore used at every
       maturity for a given valuation date.

    Notes
    -----
    A faithful quarterly implementation requires a sufficiently long and
    densely sampled maturity surface. With daily tenors from about 20 to 730
    days and ``transition_step_days=90``, there are roughly 621 maturity-pair
    equations for a 150-state transition matrix.

    One-day transitions are also supported. For a grid containing 5, 6, ...,
    34 days, ``transition_step_days=1`` uses the 29 adjacent maturity pairs.
    Such a system is underdetermined when the recovery grid has more than 29
    states; this is allowed because ridge regularization supplies a solution,
    but the condition, rank, fit, sparsity, and spectral diagnostics will flag
    the identification weakness.
    """

    def __init__(
        self,
        *,
        recovery_grid_size: Optional[int] = 150,
        recovery_grid_bounds: Optional[Tuple[float, float]] = None,
        transition_step_days: int = 90,
        maturity_pair_tolerance_days: float = 0.51,
        min_transition_pairs: Optional[int] = None,
        zeta_grid: Optional[np.ndarray] = None,
        state_price_floor: float = 1e-20,
        current_state: float = 0.0,
        nnls_max_iter: int = 500,
        eigenvector_negative_tolerance: float = 1e-10,
        eigenpair_residual_tolerance: float = 1e-7,
        key_spec: KeySpec = KeySpec(),
        eps: float = 1e-10,
        verbose: bool = True,
        penalty_value: float = 1e100,
        cache_spec: CacheSpec = CacheSpec(),
        behavioral: bool = False,
        stock_df=None,
        stock_date_col: str = "date",
        volume_col: str = "volume",
        k1: float = 1.0,
        k2: float = 1.2,
        k3: float = 1.0,
        sentiment_alpha: float = 0.05,
        **kwargs,
    ):
        super().__init__(
            key_spec=key_spec,
            min_obs=1,
            eps=eps,
            verbose=verbose,
            penalty_value=penalty_value,
            cache_spec=cache_spec,
            behavioral=behavioral,
            stock_df=stock_df,
            stock_date_col=stock_date_col,
            volume_col=volume_col,
            k1=k1,
            k2=k2,
            k3=k3,
            sentiment_alpha=sentiment_alpha,
        )

        if recovery_grid_size is None:
            self.recovery_grid_size = None
        else:
            recovery_grid_size = int(recovery_grid_size)
            if recovery_grid_size < 10:
                raise ValueError(
                    "recovery_grid_size must be at least 10 or None."
                )
            self.recovery_grid_size = recovery_grid_size

        if recovery_grid_bounds is None:
            self.recovery_grid_bounds = None
        else:
            if len(recovery_grid_bounds) != 2:
                raise ValueError(
                    "recovery_grid_bounds must contain (lower, upper)."
                )
            lower, upper = map(float, recovery_grid_bounds)
            if (
                not np.isfinite(lower)
                or not np.isfinite(upper)
                or lower >= upper
            ):
                raise ValueError(
                    "recovery_grid_bounds must be finite and increasing."
                )
            self.recovery_grid_bounds = (lower, upper)

        self.transition_step_days = int(transition_step_days)
        if self.transition_step_days < 1:
            raise ValueError("transition_step_days must be at least 1.")

        self.maturity_pair_tolerance_days = float(
            maturity_pair_tolerance_days
        )
        if (
            not np.isfinite(self.maturity_pair_tolerance_days)
            or self.maturity_pair_tolerance_days < 0
        ):
            raise ValueError(
                "maturity_pair_tolerance_days must be finite and nonnegative."
            )

        self.min_transition_pairs = (
            None
            if min_transition_pairs is None
            else int(min_transition_pairs)
        )
        if (
            self.min_transition_pairs is not None
            and self.min_transition_pairs < 2
        ):
            raise ValueError("min_transition_pairs must be at least 2.")

        self.zeta_grid = (
            np.asarray(zeta_grid, dtype=float).ravel()
            if zeta_grid is not None
            else np.linspace(0.0, 0.2, 41)
        )
        if self.zeta_grid.size == 0:
            raise ValueError("zeta_grid cannot be empty.")
        if (
            np.any(~np.isfinite(self.zeta_grid))
            or np.any(self.zeta_grid < 0)
        ):
            raise ValueError(
                "zeta_grid must contain finite nonnegative values."
            )

        self.state_price_floor = float(state_price_floor)
        if self.state_price_floor <= 0:
            raise ValueError("state_price_floor must be positive.")

        self.current_state = float(current_state)
        self.nnls_max_iter = int(nnls_max_iter)
        if self.nnls_max_iter < 1:
            raise ValueError("nnls_max_iter must be at least 1.")

        self.eigenvector_negative_tolerance = float(
            eigenvector_negative_tolerance
        )
        self.eigenpair_residual_tolerance = float(
            eigenpair_residual_tolerance
        )

        self.is_fitted_ = True

    def fit(self, *args, **kwargs):
        self.is_fitted_ = True
        return self

    def _cache_params(self) -> dict:
        return {
            "recovery_grid_size": self.recovery_grid_size,
            "recovery_grid_bounds": self.recovery_grid_bounds,
            "transition_step_days": self.transition_step_days,
            "maturity_pair_tolerance_days":
                self.maturity_pair_tolerance_days,
            "min_transition_pairs": self.min_transition_pairs,
            "zeta_grid": self.zeta_grid,
            "state_price_floor": self.state_price_floor,
            "current_state": self.current_state,
            "nnls_max_iter": self.nnls_max_iter,
            "eigenvector_negative_tolerance":
                self.eigenvector_negative_tolerance,
            "eigenpair_residual_tolerance":
                self.eigenpair_residual_tolerance,
        }

    def transform_info(
        self,
        info: dict,
        *,
        bootstrap: bool = False,
        bootstrap_spec: BootstrapSpec = BootstrapSpec(),
    ) -> dict:
        return self.transform_rnd(
            info,
            bootstrap=bootstrap,
            bootstrap_spec=bootstrap_spec,
        )

    def transform_rnd(
        self,
        info: dict,
        *,
        bootstrap: bool = False,
        bootstrap_spec: BootstrapSpec = BootstrapSpec(),
    ) -> dict:
        original_x, original_rnd, original_cdf, T_grid = (
            self._extract_surfaces(info)
        )
        original_x = _as_1d(original_x)
        T_grid = _as_1d(T_grid)

        self._validate_surface(
            x_grid=original_x,
            surface=original_rnd,
            T_grid=T_grid,
        )

        S0 = _find_spot(info, self.key_spec.spot_keys)

        rnd_lr_surface = np.vstack([
            _trapz_normalize_density(
                original_x,
                original_rnd[j],
                eps=self.eps,
            )
            for j in range(T_grid.size)
        ])
        if np.any(~np.isfinite(rnd_lr_surface)):
            raise ValueError(
                "At least one original risk-neutral density is invalid."
            )

        cdf_lr_surface = self._clean_or_rebuild_cdf_surface(
            x_grid=original_x,
            rnd_lr_surface=rnd_lr_surface,
            supplied_cdf=original_cdf,
        )

        # Estimate the transition matrix and Perron vector on a coarse grid.
        recovery_x = self._build_recovery_grid(original_x)
        recovery_rnd = self._interpolate_density_surface(
            source_x=original_x,
            target_x=recovery_x,
            surface=rnd_lr_surface,
        )

        recovery = self._estimate_recovery_from_surface(
            x_grid=recovery_x,
            rnd_lr_surface=recovery_rnd,
            T_grid=T_grid,
            info=info,
            original_grid_size=original_x.size,
        )

        # Interpolate the right Perron vector, not the recovered density.
        z_full = self._interpolate_eigenfunction(
            source_x=recovery_x,
            target_x=original_x,
            z=recovery.eigenfunction,
        )

        # Normalize z at the current state. Its scale is otherwise arbitrary.
        i0_full = int(
            np.argmin(np.abs(original_x - self.current_state))
        )
        z_at_current = float(z_full[i0_full])
        if not np.isfinite(z_at_current) or z_at_current <= self.eps:
            raise ValueError(
                "Interpolated Perron vector is invalid at current state."
            )
        z_full = z_full / z_at_current

        kernel_full = 1.0 / np.maximum(z_full, self.eps)
        kernel_full = kernel_full / kernel_full[i0_full]

        # Keep the user's existing scalar-rate discount treatment.
        state_price_full = self._state_price_matrix(
            original_x,
            rnd_lr_surface,
            T_grid,
            info,
        )

        # Audrino-style cross-sectional recovery:
        # physical mass is proportional to z * observed state-price mass.
        physical_lr_surface = self._physical_surface_from_eigenfunction(
            x_grid=original_x,
            state_price_matrix=state_price_full,
            z=z_full,
        )

        physical_cdf_lr_surface = np.vstack([
            _cdf_from_density(
                original_x,
                physical_lr_surface[j],
                eps=self.eps,
            )
            for j in range(T_grid.size)
        ])

        pricing_kernel_surface = np.tile(
            kernel_full,
            (T_grid.size, 1),
        )

        measure_weight_surface = np.tile(
            z_full,
            (T_grid.size, 1),
        )

        rra_surface = np.vstack([
            self.compute_relative_risk_aversion(
                original_x,
                kernel_full,
            )
            for _ in range(T_grid.size)
        ])

        grid_lr, grid_r, grid_k = build_axis_grids(
            original_x,
            S0,
        )

        rnd_r_surface = lr_surface_to_r_surface(
            rnd_lr_surface,
            grid_r,
        )
        physical_r_surface = lr_surface_to_r_surface(
            physical_lr_surface,
            grid_r,
        )

        rnd_k_surface = lr_surface_to_k_surface(
            rnd_lr_surface,
            grid_k,
        )
        physical_k_surface = lr_surface_to_k_surface(
            physical_lr_surface,
            grid_k,
        )

        physical_moments = physical_moments_table(
            T_grid=T_grid,
            r_grid=grid_lr,
            physical_lr_surface=physical_lr_surface,
        )
        risk_neutral_moments = physical_moments_table(
            T_grid=T_grid,
            r_grid=grid_lr,
            physical_lr_surface=rnd_lr_surface,
        )

        status_by_T = [
            {
                "T": float(T),
                "matched_T": float(T),
                "status": "success",
                "ross_recovery_grid_size": int(recovery_x.size),
                "transition_step_days":
                    int(self.transition_step_days),
            }
            for T in T_grid
        ]

        out = build_transform_output(
            method_name=self.method_name,
            info=info,
            fit_trim_alpha=None,
            T_grid=T_grid,
            matched_T_grid=T_grid,
            status_by_T=status_by_T,
            grid_lr=grid_lr,
            grid_r=grid_r,
            grid_k=grid_k,
            rnd_lr_surface=rnd_lr_surface,
            rnd_r_surface=rnd_r_surface,
            rnd_k_surface=rnd_k_surface,
            cdf_lr_surface=cdf_lr_surface,
            cdf_r_surface=cdf_lr_surface,
            cdf_k_surface=cdf_lr_surface,
            base_physical_lr_surface=physical_lr_surface,
            base_physical_r_surface=physical_r_surface,
            base_physical_k_surface=physical_k_surface,
            base_physical_cdf_lr_surface=physical_cdf_lr_surface,
            base_physical_cdf_r_surface=physical_cdf_lr_surface,
            base_physical_cdf_k_surface=physical_cdf_lr_surface,
            physical_lr_surface=physical_lr_surface,
            physical_r_surface=physical_r_surface,
            physical_k_surface=physical_k_surface,
            physical_cdf_lr_surface=physical_cdf_lr_surface,
            physical_cdf_r_surface=physical_cdf_lr_surface,
            physical_cdf_k_surface=physical_cdf_lr_surface,
            pricing_kernel_surface=pricing_kernel_surface,
            rra_surface=rra_surface,
            measure_weight_surface=measure_weight_surface,
            base_pricing_kernel_surface=pricing_kernel_surface,
            base_measure_weight_surface=measure_weight_surface,
            fit_diagnostics={},
            S0=S0,
            physical_moments=physical_moments,
            risk_neutral_moments=risk_neutral_moments,
            base_physical_moments=physical_moments,
        )

        out["ross_recovery"] = recovery.__dict__
        out["ross_recovery"]["eigenfunction_original_grid"] = (
            z_full.copy()
        )
        out["ross_recovery"][
            "pricing_kernel_original_grid"
        ] = kernel_full.copy()

        out["ross_recovery_diagnostics"] = {
            "transition_system_shape": (
                int(recovery.transition_system_rows),
                int(recovery.transition_system_columns),
            ),
            "transition_system_rank":
                int(recovery.transition_system_rank),
            "transition_system_condition_number":
                float(
                    recovery.transition_system_condition_number
                ),
            "transition_pair_count":
                int(recovery.transition_pair_count),
            "transition_fit_rmse":
                float(recovery.transition_fit_rmse),
            "transition_fit_relative_rmse":
                float(
                    recovery.transition_fit_relative_rmse
                ),
            "unrolled_state_price_rmse":
                float(
                    recovery.selected_kl_reconstruction_rmse
                ),
            "unrolled_state_price_relative_rmse":
                float(
                    recovery
                    .selected_kl_reconstruction_relative_rmse
                ),
            "selected_zeta":
                float(recovery.ridge_zeta),
            "selected_generalized_kl":
                float(recovery.kl_loss),
            "dominant_eigenvalue":
                float(recovery.dominant_eigenvalue),
            "subdominant_eigenvalue_abs":
                float(
                    recovery.subdominant_eigenvalue_abs
                ),
            "subdominant_to_dominant_ratio":
                float(
                    recovery
                    .subdominant_to_dominant_ratio
                ),
            "eigenpair_residual":
                float(recovery.eigenpair_residual),
            "eigenpair_residual_tolerance":
                float(self.eigenpair_residual_tolerance),
            "eigenpair_residual_exceeds_tolerance":
                bool(
                    recovery.eigenpair_residual
                    > self.eigenpair_residual_tolerance
                ),
            "physical_transition_max_row_sum_error":
                float(
                    recovery
                    .recovered_transition_row_sum_error
                ),
            "transition_matrix_zero_fraction":
                float(
                    recovery
                    .transition_matrix_zero_fraction
                ),
            "transition_matrix_row_sum_range": (
                float(
                    recovery
                    .transition_matrix_min_row_sum
                ),
                float(
                    recovery
                    .transition_matrix_max_row_sum
                ),
            ),
            "warnings":
                list(recovery.diagnostic_warnings),
            "zeta_values_tested":
                recovery.zeta_values_tested.copy(),
            "zeta_kl_values":
                recovery.zeta_kl_values.copy(),
        }

        out["ross_recovery_settings"] = {
            "original_grid_size": int(original_x.size),
            "recovery_grid_size": int(recovery_x.size),
            "requested_recovery_grid_size":
                self.recovery_grid_size,
            "recovery_grid_bounds": (
                float(recovery_x[0]),
                float(recovery_x[-1]),
            ),
            "transition_step_days":
                int(self.transition_step_days),
            "maturity_pair_tolerance_days":
                float(self.maturity_pair_tolerance_days),
            "transition_pair_count":
                int(recovery.transition_pair_count),
            "zeta_grid_size": int(self.zeta_grid.size),
            "nnls_max_iter": int(self.nnls_max_iter),
            "eigenpair_residual_tolerance":
                float(self.eigenpair_residual_tolerance),
            "eigenpair_residual_is_fatal": False,
            "interpolated_quantity":
                "right Perron eigenvector",
            "eigenvector_interpolation":
                "PCHIP",
            "physical_recovery":
                "z_times_observed_state_price_mass",
            "common_kernel_across_maturities": True,
        }

        out["bootstrap"] = {
            "enabled": False,
            "requested": bool(bootstrap),
            "message": (
                "Ross recovery bootstrap is not implemented."
                if bootstrap
                else None
            ),
        }

        return out

    def _fit_one_maturity(self, *args, **kwargs):
        raise NotImplementedError(
            "RossRecoveryKernel does not use _fit_one_maturity(). "
            "Use transform_rnd(info) instead."
        )

    def _transform_surface_with_model(self, *args, **kwargs):
        raise NotImplementedError(
            "RossRecoveryKernel does not use "
            "_transform_surface_with_model(). "
            "Use transform_rnd(info) instead."
        )

    def _validate_surface(
        self,
        *,
        x_grid,
        surface,
        T_grid,
    ) -> None:
        x = _as_1d(x_grid)
        T = _as_1d(T_grid)
        Z = np.asarray(surface, dtype=float)

        if x.size < 2 or np.any(~np.isfinite(x)):
            raise ValueError(
                "x_grid must contain at least two finite values."
            )
        if np.any(np.diff(x) <= 0):
            raise ValueError("x_grid must be strictly increasing.")

        if T.size < 3:
            raise ValueError(
                "Ross recovery needs at least three maturities."
            )
        if np.any(~np.isfinite(T)) or np.any(np.diff(T) <= 0):
            raise ValueError(
                "T_grid must be finite and strictly increasing."
            )

        if Z.shape != (T.size, x.size):
            raise ValueError(
                "rnd_lr_surface must have shape "
                f"{(T.size, x.size)}, got {Z.shape}."
            )

    def _build_recovery_grid(
        self,
        original_x: np.ndarray,
    ) -> np.ndarray:
        x = _as_1d(original_x)

        if self.recovery_grid_bounds is None:
            lower, upper = float(x[0]), float(x[-1])
        else:
            lower, upper = self.recovery_grid_bounds
            if lower < float(x[0]) or upper > float(x[-1]):
                raise ValueError(
                    "recovery_grid_bounds must lie inside "
                    "the original x grid."
                )

        if not (lower <= self.current_state <= upper):
            raise ValueError(
                "current_state must lie inside recovery_grid_bounds."
            )

        if self.recovery_grid_size is None:
            recovery_x = x[(x >= lower) & (x <= upper)]
            if recovery_x.size < 10:
                raise ValueError(
                    "The selected bounds contain fewer than 10 states."
                )
            return recovery_x.copy()

        n_states = min(
            int(self.recovery_grid_size),
            int(x.size),
        )
        if n_states < 10:
            raise ValueError(
                "The effective recovery grid must have at least 10 states."
            )

        return np.linspace(
            lower,
            upper,
            n_states,
            dtype=float,
        )

    def _interpolate_density_surface(
        self,
        *,
        source_x,
        target_x,
        surface,
    ) -> np.ndarray:
        source_x = _as_1d(source_x)
        target_x = _as_1d(target_x)
        surface = np.asarray(surface, dtype=float)

        if (
            surface.ndim != 2
            or surface.shape[1] != source_x.size
        ):
            raise ValueError(
                "surface must be 2D with one column "
                "for each source_x state."
            )

        rows = []

        for row in surface:
            row = np.where(
                np.isfinite(row) & (row >= 0),
                row,
                0.0,
            )

            interpolated = np.interp(
                target_x,
                source_x,
                row,
                left=0.0,
                right=0.0,
            )

            interpolated = _trapz_normalize_density(
                target_x,
                interpolated,
                eps=self.eps,
            )

            if np.any(~np.isfinite(interpolated)):
                raise ValueError(
                    "A density row could not be normalized "
                    "after interpolation."
                )

            rows.append(interpolated)

        return np.vstack(rows)

    def _interpolate_eigenfunction(
        self,
        *,
        source_x,
        target_x,
        z,
    ) -> np.ndarray:
        """
        Interpolate the positive Perron vector with PCHIP.

        PCHIP is shape preserving and avoids the negative overshoot that can
        occur when a sparse positive eigenvector is interpolated with an
        unconstrained cubic spline.
        """
        source_x = _as_1d(source_x)
        target_x = _as_1d(target_x)
        z = _as_1d(z)

        if source_x.size != z.size:
            raise ValueError(
                "source_x and z must have the same length."
            )
        if source_x.size < 2:
            raise ValueError(
                "PCHIP interpolation needs at least two states."
            )
        if np.any(~np.isfinite(source_x)) or np.any(np.diff(source_x) <= 0):
            raise ValueError(
                "source_x must be finite and strictly increasing."
            )
        if np.any(~np.isfinite(z)) or np.any(z <= 0):
            raise ValueError(
                "The Perron eigenvector must be finite and positive."
            )

        interpolator = PchipInterpolator(
            source_x,
            z,
            extrapolate=False,
        )
        z_full = np.asarray(
            interpolator(target_x),
            dtype=float,
        )

        outside = (
            (target_x < source_x[0])
            | (target_x > source_x[-1])
        )
        z_full[outside] = np.nan

        if np.any(~np.isfinite(z_full)):
            raise ValueError(
                "The recovery grid must cover the complete output grid."
            )

        scale = max(
            float(np.max(np.abs(z))),
            1.0,
        )
        negative_tol = (
            self.eigenvector_negative_tolerance * scale
        )
        min_z_full = float(np.min(z_full))

        if min_z_full < -negative_tol:
            raise ValueError(
                "PCHIP interpolation produced materially negative "
                "Perron-vector values. Check the recovery grid and "
                "eigenvector diagnostics."
            )

        z_full = np.maximum(
            z_full,
            self.eps,
        )
        return z_full

    def _clean_or_rebuild_cdf_surface(
        self,
        *,
        x_grid,
        rnd_lr_surface,
        supplied_cdf,
    ) -> np.ndarray:
        x = _as_1d(x_grid)
        supplied = np.asarray(
            supplied_cdf,
            dtype=float,
        )

        if (
            supplied.shape == rnd_lr_surface.shape
            and np.all(np.isfinite(supplied))
        ):
            cleaned = np.maximum.accumulate(
                np.clip(supplied, 0.0, 1.0),
                axis=1,
            )
            spans = cleaned[:, -1] - cleaned[:, 0]

            if (
                np.all(np.isfinite(spans))
                and np.all(spans > self.eps)
            ):
                cleaned = (
                    cleaned - cleaned[:, [0]]
                ) / spans[:, None]
                cleaned[:, 0] = 0.0
                cleaned[:, -1] = 1.0
                return cleaned

        return np.vstack([
            _cdf_from_density(
                x,
                row,
                eps=self.eps,
            )
            for row in rnd_lr_surface
        ])

    def _state_price_matrix(
        self,
        x_grid,
        rnd_lr_surface,
        T_grid,
        info,
    ) -> np.ndarray:
        """
        Build state-price masses.

        The scalar-rate discount treatment is intentionally retained from
        the previous implementation, as requested.
        """
        r_rate = float(info.get("r", 0.0))
        if not np.isfinite(r_rate):
            r_rate = 0.0

        x = _as_1d(x_grid)
        T_grid = _as_1d(T_grid)
        dx = np.gradient(x)

        columns = []

        for j, T in enumerate(T_grid):
            f_q = _trapz_normalize_density(
                x,
                rnd_lr_surface[j],
                eps=self.eps,
            )
            if np.any(~np.isfinite(f_q)):
                raise ValueError(
                    f"Invalid RND at maturity index {j}."
                )

            discount = np.exp(
                -r_rate * float(T)
            )
            state_prices = (
                discount
                * f_q
                * dx
            )

            columns.append(
                np.maximum(
                    state_prices,
                    self.state_price_floor,
                )
            )

        return np.column_stack(columns)

    def _maturity_pair_indices(
        self,
        T_grid,
    ) -> Tuple[np.ndarray, np.ndarray]:
        T_days = 365.0 * _as_1d(T_grid)
        step = float(self.transition_step_days)
        tol = float(self.maturity_pair_tolerance_days)

        source_indices = []
        target_indices = []

        for i, day in enumerate(T_days):
            target_day = day + step
            j = int(
                np.argmin(
                    np.abs(T_days - target_day)
                )
            )

            if (
                j > i
                and abs(T_days[j] - target_day) <= tol
            ):
                source_indices.append(i)
                target_indices.append(j)

        if not source_indices:
            min_day = float(np.min(T_days))
            max_day = float(np.max(T_days))
            raise ValueError(
                "No maturity pairs are separated by "
                f"{self.transition_step_days} days within tolerance "
                f"{tol:g}. Available maturity range is "
                f"{min_day:.2f} to {max_day:.2f} days."
            )

        source = np.asarray(
            source_indices,
            dtype=int,
        )
        target = np.asarray(
            target_indices,
            dtype=int,
        )

        required = (
            self.min_transition_pairs
            if self.min_transition_pairs is not None
            else 2
        )

        if source.size < required:
            raise ValueError(
                f"Only {source.size} usable maturity pairs were found; "
                f"at least {required} are required."
            )

        return source, target

    def _kl_maturity_indices(
        self,
        T_grid,
    ) -> np.ndarray:
        """
        Select maturities corresponding to one, two, ... transition steps
        beyond the shortest available maturity.

        With a 20-day lower boundary and a 90-day transition, this selects
        approximately 110, 200, 290, 380, ... days.
        """
        T_days = 365.0 * _as_1d(T_grid)
        base_day = float(T_days[0])
        max_day = float(T_days[-1])
        step = float(self.transition_step_days)
        tol = float(self.maturity_pair_tolerance_days)

        indices = []
        k = 1

        while base_day + k * step <= max_day + tol:
            target_day = base_day + k * step
            j = int(
                np.argmin(
                    np.abs(T_days - target_day)
                )
            )

            if abs(T_days[j] - target_day) <= tol:
                indices.append(j)

            k += 1

        if not indices:
            raise ValueError(
                "The maturity surface contains no tenors compatible "
                "with unrolling the selected transition step."
            )

        return np.asarray(
            indices,
            dtype=int,
        )

    def _estimate_recovery_from_surface(
        self,
        *,
        x_grid,
        rnd_lr_surface,
        T_grid,
        info,
        original_grid_size: int,
    ) -> RossRecoveryOutput:
        x = _as_1d(x_grid)
        T_grid = _as_1d(T_grid)

        S = self._state_price_matrix(
            x,
            rnd_lr_surface,
            T_grid,
            info,
        )

        source_idx, target_idx = (
            self._maturity_pair_indices(T_grid)
        )

        A = S[:, source_idx].T
        B = S[:, target_idx].T

        if A.shape[0] < 2:
            raise ValueError(
                "At least two maturity-pair equations are required."
            )

        # Identification and conditioning diagnostics for A.
        transition_rank = int(
            np.linalg.matrix_rank(A)
        )
        singular_values = np.linalg.svd(
            A,
            compute_uv=False,
        )
        if (
            singular_values.size == 0
            or not np.isfinite(singular_values[0])
        ):
            condition_number = np.inf
        elif singular_values[-1] <= np.finfo(float).eps:
            condition_number = np.inf
        else:
            condition_number = float(
                singular_values[0]
                / singular_values[-1]
            )

        i0 = int(
            np.argmin(
                np.abs(x - self.current_state)
            )
        )

        kl_idx = self._kl_maturity_indices(
            T_grid
        )
        S_kl = S[:, kl_idx]

        best = None
        zeta_values = []
        zeta_kl_values = []

        for zeta in self.zeta_grid:
            zeta = float(zeta)

            G = self._solve_transition_nnls(
                A,
                B,
                zeta,
            )

            U = self._markov_state_prices(
                G,
                i0=i0,
                n_steps=kl_idx.size,
            )

            kl = self._generalized_kl(
                S_kl,
                U,
            )

            zeta_values.append(zeta)
            zeta_kl_values.append(float(kl))

            if (
                best is None
                or kl < best["kl"]
            ):
                best = {
                    "zeta": zeta,
                    "G": G,
                    "U": U,
                    "kl": float(kl),
                }

        if best is None:
            raise RuntimeError(
                "Ross recovery failed for every ridge penalty."
            )

        # Transition fit diagnostics.
        transition_residual = (
            A @ best["G"] - B
        )
        transition_fit_rmse = float(
            np.sqrt(
                np.mean(
                    transition_residual ** 2
                )
            )
        )
        B_rms = float(
            np.sqrt(
                np.mean(
                    B ** 2
                )
            )
        )
        transition_fit_relative_rmse = float(
            transition_fit_rmse
            / max(B_rms, self.state_price_floor)
        )

        kl_residual = best["U"] - S_kl
        selected_kl_rmse = float(
            np.sqrt(
                np.mean(
                    kl_residual ** 2
                )
            )
        )
        S_kl_rms = float(
            np.sqrt(
                np.mean(
                    S_kl ** 2
                )
            )
        )
        selected_kl_relative_rmse = float(
            selected_kl_rmse
            / max(S_kl_rms, self.state_price_floor)
        )

        G = best["G"]
        zero_tolerance = max(
            self.state_price_floor,
            1e-14,
        )
        transition_zero_fraction = float(
            np.mean(G <= zero_tolerance)
        )
        transition_row_sums = G.sum(axis=1)
        transition_min_row_sum = float(
            np.min(transition_row_sums)
        )
        transition_max_row_sum = float(
            np.max(transition_row_sums)
        )

        (
            physical_transition,
            lam,
            z,
            spectral,
        ) = self._ross_recover(G)

        kernel_recovery = (
            1.0 / np.maximum(z, self.eps)
        )
        kernel_recovery /= kernel_recovery[i0]

        warnings = []

        if A.shape[0] < A.shape[1]:
            warnings.append(
                "transition_system_underdetermined"
            )

        if transition_rank < min(A.shape):
            warnings.append(
                "transition_design_rank_deficient"
            )

        if (
            not np.isfinite(condition_number)
            or condition_number > 1e12
        ):
            warnings.append(
                "transition_design_extremely_ill_conditioned"
            )
        elif condition_number > 1e8:
            warnings.append(
                "transition_design_ill_conditioned"
            )

        if transition_fit_relative_rmse > 0.25:
            warnings.append(
                "transition_fit_relative_rmse_large"
            )

        if selected_kl_relative_rmse > 0.25:
            warnings.append(
                "unrolled_state_price_fit_relative_rmse_large"
            )

        if transition_zero_fraction > 0.90:
            warnings.append(
                "transition_matrix_extremely_sparse"
            )
        elif transition_zero_fraction > 0.75:
            warnings.append(
                "transition_matrix_sparse"
            )

        if not (0.0 < lam < 1.0):
            warnings.append(
                "dominant_eigenvalue_outside_discount_factor_range"
            )

        if (
            np.isfinite(spectral["subdominant_ratio"])
            and spectral["subdominant_ratio"] > 0.95
        ):
            warnings.append(
                "small_spectral_gap_recovery_sensitive"
            )

        if (
            np.isfinite(spectral["eigenpair_residual"])
            and spectral["eigenpair_residual"]
            > self.eigenpair_residual_tolerance
        ):
            warnings.append(
                "poor_dominant_eigenpair_residual"
            )

        if (
            source_idx.size < x.size
        ):
            warnings.append(
                "fewer_maturity_pairs_than_recovery_states"
            )

        if self.verbose:
            warning_text = (
                ",".join(warnings)
                if warnings
                else "none"
            )
            print(
                "[ross] "
                f"original_states={int(original_grid_size)} | "
                f"recovery_states={x.size} | "
                f"maturities={T_grid.size} | "
                f"transition_step={self.transition_step_days}d | "
                f"pairs={source_idx.size} | "
                f"A_shape={A.shape} | "
                f"rank={transition_rank} | "
                f"cond={condition_number:.3e} | "
                f"zeta={best['zeta']:.6g} | "
                f"KL={best['kl']:.6g} | "
                f"transition_rel_rmse="
                f"{transition_fit_relative_rmse:.3e} | "
                f"unrolled_rel_rmse="
                f"{selected_kl_relative_rmse:.3e} | "
                f"lambda={lam:.6g} | "
                f"sub/dom="
                f"{spectral['subdominant_ratio']:.6g} | "
                f"warnings={warning_text}"
            )

        return RossRecoveryOutput(
            state_price_matrix=S,
            state_price_transition=G,
            physical_transition=physical_transition,
            eigenvalue=float(lam),
            eigenfunction=z,
            pricing_kernel_recovery_grid=kernel_recovery,
            ridge_zeta=float(best["zeta"]),
            kl_loss=float(best["kl"]),
            current_state_index=int(i0),
            transition_step_days=int(
                self.transition_step_days
            ),
            transition_step_years=float(
                self.transition_step_days / 365.0
            ),
            transition_pair_count=int(
                source_idx.size
            ),
            transition_source_indices=source_idx,
            transition_target_indices=target_idx,
            kl_maturity_indices=kl_idx,
            dominant_eigenvalue=float(lam),
            subdominant_eigenvalue_abs=float(
                spectral["subdominant_abs"]
            ),
            subdominant_to_dominant_ratio=float(
                spectral["subdominant_ratio"]
            ),
            eigenpair_residual=float(
                spectral["eigenpair_residual"]
            ),
            recovered_transition_row_sum_error=float(
                spectral["row_sum_error"]
            ),
            transition_system_rows=int(A.shape[0]),
            transition_system_columns=int(A.shape[1]),
            transition_system_rank=int(
                transition_rank
            ),
            transition_system_condition_number=float(
                condition_number
            ),
            transition_fit_rmse=float(
                transition_fit_rmse
            ),
            transition_fit_relative_rmse=float(
                transition_fit_relative_rmse
            ),
            transition_matrix_zero_fraction=float(
                transition_zero_fraction
            ),
            transition_matrix_min_row_sum=float(
                transition_min_row_sum
            ),
            transition_matrix_max_row_sum=float(
                transition_max_row_sum
            ),
            selected_kl_reconstruction_rmse=float(
                selected_kl_rmse
            ),
            selected_kl_reconstruction_relative_rmse=float(
                selected_kl_relative_rmse
            ),
            zeta_values_tested=np.asarray(
                zeta_values,
                dtype=float,
            ),
            zeta_kl_values=np.asarray(
                zeta_kl_values,
                dtype=float,
            ),
            diagnostic_warnings=tuple(warnings),
            recovery_grid=x.copy(),
            recovery_grid_size=int(x.size),
            original_grid_size=int(
                original_grid_size
            ),
            recovery_grid_bounds=(
                float(x[0]),
                float(x[-1]),
            ),
        )

    def _solve_transition_nnls(
        self,
        A,
        B,
        zeta,
    ) -> np.ndarray:
        A = np.asarray(A, dtype=float)
        B = np.asarray(B, dtype=float)

        if A.ndim != 2 or B.ndim != 2:
            raise ValueError(
                "A and B must both be two-dimensional."
            )
        if A.shape != B.shape:
            raise ValueError(
                "A and B must have the same shape."
            )

        n_states = A.shape[1]
        G = np.zeros(
            (n_states, n_states),
            dtype=float,
        )

        if zeta > 0:
            A_aug = np.vstack([
                A,
                np.sqrt(zeta)
                * np.eye(n_states),
            ])
        else:
            A_aug = A

        for j in range(n_states):
            b = B[:, j]

            if zeta > 0:
                b_aug = np.r_[
                    b,
                    np.zeros(n_states),
                ]
            else:
                b_aug = b

            result = lsq_linear(
                A_aug,
                b_aug,
                bounds=(0.0, np.inf),
                method="trf",
                lsmr_tol="auto",
                max_iter=self.nnls_max_iter,
            )

            if (
                not result.success
                and self.verbose
            ):
                print(
                    "[ross warning] "
                    f"NNLS column {j} did not converge: "
                    f"{result.message}"
                )

            if np.any(~np.isfinite(result.x)):
                raise ValueError(
                    f"NNLS returned nonfinite values in column {j}."
                )

            G[:, j] = np.maximum(
                result.x,
                0.0,
            )

        # Do not add a positive floor to the transition matrix. The paper's
        # small constant is used in the KL calculation, not to alter P.
        return G

    def _markov_state_prices(
        self,
        G,
        *,
        i0,
        n_steps,
    ) -> np.ndarray:
        G = np.asarray(G, dtype=float)
        n_states = G.shape[0]

        U = np.zeros(
            (n_states, int(n_steps)),
            dtype=float,
        )

        row = np.zeros(
            n_states,
            dtype=float,
        )
        row[int(i0)] = 1.0

        for k in range(int(n_steps)):
            row = row @ G
            U[:, k] = row

        return np.maximum(
            U,
            self.state_price_floor,
        )

    def _generalized_kl(
        self,
        S,
        U,
    ) -> float:
        S = np.maximum(
            np.asarray(S, dtype=float),
            self.state_price_floor,
        )
        U = np.maximum(
            np.asarray(U, dtype=float),
            self.state_price_floor,
        )

        if S.shape != U.shape:
            raise ValueError(
                "S and U must have the same shape "
                "for generalized KL evaluation."
            )

        value = np.sum(
            S * np.log(S / U)
            - (S - U)
        )

        return (
            float(value)
            if np.isfinite(value)
            else np.inf
        )

    def _ross_recover(
        self,
        G,
    ):
        G = np.asarray(G, dtype=float)

        values, vectors = eig(G)

        finite = (
            np.isfinite(np.real(values))
            & np.isfinite(np.imag(values))
        )
        if not np.any(finite):
            raise ValueError(
                "The transition matrix has no finite eigenvalues."
            )

        candidates = np.where(finite)[0]
        idx = int(
            candidates[
                np.argmax(
                    np.real(values[candidates])
                )
            ]
        )

        lam_complex = values[idx]
        if abs(float(np.imag(lam_complex))) > 1e-8:
            raise ValueError(
                "The dominant eigenvalue is materially complex."
            )

        lam = float(np.real(lam_complex))
        if not np.isfinite(lam) or lam <= self.eps:
            raise ValueError(
                "Ross recovery requires a positive "
                "dominant eigenvalue."
            )

        z_complex = vectors[:, idx]
        if np.max(np.abs(np.imag(z_complex))) > 1e-8:
            raise ValueError(
                "The dominant right eigenvector is materially complex."
            )

        z = np.real(z_complex)

        if float(np.sum(z)) < 0:
            z = -z

        scale = max(
            float(np.max(np.abs(z))),
            1.0,
        )
        negative_tol = (
            self.eigenvector_negative_tolerance
            * scale
        )

        if float(np.min(z)) < -negative_tol:
            raise ValueError(
                "The dominant right eigenvector is not positive. "
                "The estimated transition matrix does not satisfy "
                "the required Perron recovery condition."
            )

        z = np.maximum(
            z,
            self.eps,
        )
        z /= np.mean(z)

        eigenpair_residual = float(
            np.linalg.norm(
                G @ z - lam * z
            )
            / max(
                np.linalg.norm(z),
                self.eps,
            )
        )

        # A poor eigenpair residual is diagnostic, not fatal. It is
        # recorded as a warning by _estimate_recovery_from_surface(), while
        # the recovered forecast remains available to the backtest.

        physical_transition = (
            G
            * (
                z[None, :]
                / np.maximum(
                    lam * z[:, None],
                    self.eps,
                )
            )
        )
        physical_transition = np.where(
            np.isfinite(physical_transition)
            & (physical_transition >= 0),
            physical_transition,
            0.0,
        )

        row_sums = physical_transition.sum(
            axis=1,
        )
        if (
            np.any(~np.isfinite(row_sums))
            or np.any(row_sums <= self.eps)
        ):
            raise ValueError(
                "Recovered physical transition matrix "
                "has invalid row sums."
            )

        row_sum_error = float(
            np.max(
                np.abs(row_sums - 1.0)
            )
        )

        # Small numerical normalization only.
        physical_transition = (
            physical_transition
            / row_sums[:, None]
        )

        abs_values = np.sort(
            np.abs(values[finite])
        )[::-1]

        subdominant_abs = (
            float(abs_values[1])
            if abs_values.size > 1
            else np.nan
        )
        subdominant_ratio = (
            float(subdominant_abs / abs(lam))
            if (
                np.isfinite(subdominant_abs)
                and abs(lam) > self.eps
            )
            else np.nan
        )

        spectral = {
            "subdominant_abs":
                subdominant_abs,
            "subdominant_ratio":
                subdominant_ratio,
            "eigenpair_residual":
                eigenpair_residual,
            "row_sum_error":
                row_sum_error,
        }

        return (
            physical_transition,
            lam,
            z,
            spectral,
        )

    def _physical_surface_from_eigenfunction(
        self,
        *,
        x_grid,
        state_price_matrix,
        z,
    ) -> np.ndarray:
        x = _as_1d(x_grid)
        z = _as_1d(z)
        S = np.asarray(
            state_price_matrix,
            dtype=float,
        )

        if S.shape[0] != x.size:
            raise ValueError(
                "state_price_matrix must have one row per state."
            )
        if z.size != x.size:
            raise ValueError(
                "z must have one value per state."
            )

        dx = np.gradient(x)
        rows = []

        for j in range(S.shape[1]):
            recovered_mass = (
                z
                * np.maximum(
                    S[:, j],
                    0.0,
                )
            )

            total = float(
                np.sum(recovered_mass)
            )
            if (
                not np.isfinite(total)
                or total <= self.eps
            ):
                raise ValueError(
                    "Recovered physical probability mass is invalid "
                    f"at maturity index {j}."
                )

            recovered_mass = (
                recovered_mass / total
            )

            density = (
                recovered_mass
                / np.maximum(dx, self.eps)
            )
            density = _trapz_normalize_density(
                x,
                density,
                eps=self.eps,
            )

            if np.any(~np.isfinite(density)):
                raise ValueError(
                    "Recovered physical density is invalid "
                    f"at maturity index {j}."
                )

            rows.append(density)

        return np.vstack(rows)
